import { z } from "zod";
import { AuthLoginService } from "../services/auth-login.js";

const authLoginParams = z.object({
	account: z
		.string()
		.regex(/^0x[a-fA-F0-9]{40}$/)
		.describe("The Ethereum address of the user"),
	signingMessage: z
		.string()
		.describe("The signing message generated by the server"),
	signature: z
		.string()
		.describe("The signature generated by signing the message with the wallet"),
	userData: z
		.object({
			client: z.enum(["eoa", "etherspot", "base"]),
		})
		.passthrough()
		.describe("User data to be stored"),
});

type AuthLoginParams = z.infer<typeof authLoginParams>;

export const authLoginTool = {
	name: "LOGIN",
	description:
		"Authenticate a user with a signed message and create a session. First get a signing message, sign it with your wallet, then call this with the signature.",
	parameters: authLoginParams,
	execute: async (params: AuthLoginParams) => {
		try {
			const service = new AuthLoginService();
			const response = await service.execute({
				account: params.account,
				signingMessage: params.signingMessage,
				signature: params.signature,
				userData: params.userData,
			});

			return service.format(response);
		} catch (error) {
			if (error instanceof Error) {
				console.log(`Error in LOGIN tool: ${error.message}`);
				return `Error logging in: ${error.message}`;
			}
			return "An unknown error occurred while logging in";
		}
	},
} as const;
